### ISSUE TITLE
Factorio v2.0

### ISSUE THREAD

**Issue by saaadel** [raiguard/QuickbarTemplates#2]
Are you planning to port it to Factorio v2.0?

I like this mod

**Comment by hahoyer** [comment]
I tried to raise this mod to 2.0 (I can't do without it anymore) But there is a strange bug:
```
Error while running event QuickbarTemplates::on_init()
Unknown style quick_bar_window_frame
stack traceback:
	[C]: in function 'add'
	__QuickbarTemplates__/control.lua:3: in function 'create_gui'
	__QuickbarTemplates__/control.lua:25: in function 'setup_player'
	__QuickbarTemplates__/control.lua:156: in function <__QuickbarTemplates__/control.lua:153>
```

According to factorio.data (github.com/wube/factorio-data.git) there is the style quick_bar_window_frame. But why is it not found?

**Comment by saaadel** [comment]
try "quick_bar_slot_window_frame"

**Comment by hahoyer** [comment]
Used "slot_window_frame" now. This seems to be the new name for the old style.

**Comment by raiguard** [comment]
Done, sorry for the wait!
